#FROM alpine
#RUN apk add pdns-recursor lua5.3-hiredis  lua5.3-socket lua5.3-cjson lua-json4 bash rsyslog 
#RUN rm /etc/pdns/recursor.conf && ln -s /etc/powerdns/recursor.conf /etc/pdns/||true
#RUN mkdir /etc/powerdns/recursor.d -p
#RUN  adduser pdns && addgroup pdns ||true
FROM ubuntu:20.04
MAINTAINER profit <profit@ccmo.me>
# Grab powerdns bits

RUN /bin/ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && export DEBIAN_FRONTEND=noninteractive  && apt-get update &&  apt-get -y  install lua5.1 luarocks curl wget libssl-dev dnsutils gnupg2 pv && apt-get clean 
RUN /bin/ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && export DEBIAN_FRONTEND=noninteractive  && apt-get update &&   curl https://repo.powerdns.com/CBC8B383-pub.asc | apt-key add - && curl https://repo.powerdns.com/FD380FBB-pub.asc | apt-key add -  && \
echo "deb [arch=amd64] http://repo.powerdns.com/ubuntu focal-rec-master main" | tee /etc/apt/sources.list.d/pdns.list && echo "deb [arch=amd64] http://repo.powerdns.com/ubuntu focal-dnsdist-15 main" |tee -a /etc/apt/sources.list.d/pdns.list &&  echo ' Package: pdns-* \
Pin: origin repo.powerdns.com \
Pin-Priority: 600' > /etc/apt/preferences.d/pdns &&  apt-get update &&  apt-get -y  install lua5.1 luarocks curl wget pdns-recursor  liblua5.1-dev libssl-dev dnsutils dnsdist && apt-get clean 

# Grab luarocks bits
RUN luarocks install luasocket && luarocks install json4lua && luarocks install redis-lua
# Hackey mc' hackerson startup script
ADD start-pdnsd.sh /start.sh
EXPOSE 53
CMD /start.sh
RUN mkdir -p /var/run/pdns-recursor
# Copy over config files
COPY files-pdns/WHITE-dnsdist.sh /
COPY files-pdns/dnsdist.conf /etc/dnsdist/
COPY files-pdns/recursor.conf /etc/powerdns/
COPY files-pdns/rsyslog.conf /etc/rsyslog.conf
COPY files-pdns/lua/ /etc/powerdns/
RUN ln -sf /etc/dnsdist/dnsdist.conf /etc/powerdns/dnsdist.conf
#RUN mkdir /etc/powerdns/lua
