version: '2.2'


services:
  dns-robin:
#    image: m400/robin
    image: redisdnsguard/redis-dns-guard
    build:
      context: .
      dockerfile: Dockerfile-pdnsd
    ports:
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
#      - "10.1.1.1:8008:80/udp"
#      - "10.1.1.1:53:53/tcp"
#      - "10.1.1.1:53:53/udp"
#      - "10.1.1.1:53:53/tcp"
    links:
      - redis
    environment: 
     # Set a SYSLOG_HOST here if you'd like this to log to a different syslog server - name or IP
     # Logs via UDP and this gets parsed in /start.sh
     # SYSLOG_HOST: '192.168.0.1'
      - SYSLOG_HOST=127.0.0.1
      - REDIS_HOST=172.23.53.234
    container_name: dns-robin
    hostname: dns-robin
##dev
    volumes:
      #- ./files-pdns/lua/:/etc/powerdns/lua:ro,consistent
      - ./files-pdns/lua/lua-options.conf:/etc/powerdns/lua-options.conf:ro,consistent
      - ./files-pdns/lua/redisconn.lua:/etc/powerdns/redisconn.lua:ro,consistent
      - ./files-pdns/lua/sinkhole.lua:/etc/powerdns/sinkhole.lua:ro,consistent
      - ./files-pdns/lua/syslog.lua:/etc/powerdns/syslog.lua:ro,consistent
      - ./files-pdns/lua/tester.lua:/etc/powerdns/tester.lua:ro,consistent
      - /etc/coredns:/etc/coredns
      - ./userconfig:/userconfig:rw,consistent
    #ports:
    #  - 51820:51820/udp
    networks:
      dns:
        ipv4_address: 172.23.53.53
  redis:
    networks:
      dns:
        ipv4_address: 172.23.53.234
    image: redis
#    ports:
#     - 127.0.0.1:6379:6379
    volumes:
      - /var/lib/dns.redis:/data
#    command:
#      - redis-server --appendonly yes


networks:
  dns:
    external: true
#    ipam:
#      config:
#        - subnet: 172.23.53.0/24
