version: '2.2'
services:
  dns-robin:
#    image: m400/robin
    build:
      context: .
    ports:
#      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
#      - "10.200.200.1:53:53/tcp"
      - "10.200.200.1:53:53/udp"
    links:
      - redis
    environment: 
     # Set a SYSLOG_HOST here if you'd like this to log to a different syslog server - name or IP
     # Logs via UDP and this gets parsed in /start.sh
     # SYSLOG_HOST: '192.168.0.1'
      - SYSLOG_HOST=127.0.0.1
      - DNSDISTKEY=$DNSDISTKEY
    container_name: dns-robin
    hostname: dns-robin
##dev
    volumes:
      #- ./files-pdns/lua/:/etc/powerdns/lua:ro,consistent
      - ./files-pdns/lua/lua-options.conf:/etc/powerdns/lua-options.conf:ro,consistent
      - ./files-pdns/lua/redisconn.lua:/etc/powerdns/redisconn.lua:ro,consistent
      - ./files-pdns/lua/sinkhole.lua:/etc/powerdns/sinkhole.lua:ro,consistent
      - ./files-pdns/lua/syslog.lua:/etc/powerdns/syslog.lua:ro,consistent
      - ./files-pdns/lua/tester.lua:/etc/powerdns/tester.lua:ro,consistent
  redis:
    image: redis
    ports:
     - 127.0.0.1:6379:6379
    volumes:
      - /var/lib/dns.redis:/data
#    command:
#      - redis-server --appendonly yes

